version: "2"

linters:
  enable:
    - depguard
    - misspell
    - revive
  exclusions:
    rules:
      - path: _test.go
        linters:
          - errcheck
  settings:
    depguard:
      rules:
        no_exec_policy:
          files:
            - "!$test"
          deny:
            - pkg: "os/exec"
              desc: "Using os/exec to run sub processes it not allowed by policy"
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          severity: warning
          disabled: true
formatters:
  enable:
    - goimports