name: build-binary

on:
  workflow_run:
    workflows: [ "golangci-lint" ]
    types:
      - completed

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24"
      - name: Build
        run: make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            bin/amd64/*
            bin/arm64/*
            bin/wasm/*
            bin/windows/*