name: release-binary

on:
  release:
    types:
      - created
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24"
      - name: Build
        run: make
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*/selfctl*